
package com.vmrepository.repoguardwebserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddVMIImplementation", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddVMIImplementation {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "receiveVMImage", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.ReceiveVMImage")
    @ResponseWrapper(localName = "receiveVMImageResponse", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.ReceiveVMImageResponse")
    @Action(input = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/receiveVMImageRequest", output = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/receiveVMImageResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/receiveVMImage/Fault/FileNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/receiveVMImage/Fault/IOException")
    })
    public void receiveVMImage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws FileNotFoundException_Exception, IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod(operationName = "Authenticate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.AuthenticateResponse")
    @Action(input = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/AuthenticateRequest", output = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/AuthenticateResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/Authenticate/Fault/FileNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/Authenticate/Fault/IOException")
    })
    public boolean authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws FileNotFoundException_Exception, IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", className = "com.vmrepository.repoguardwebserver.UploadResponse")
    @Action(input = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/uploadRequest", output = "http://RepoGuardWebServer.vmrepository.com/AddVMIImplementation/uploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
